---
apiVersion: v1
kind: Secret
metadata:
  labels:
    agentclusterinstalls.extensions.hive.openshift.io: "true"
  name: assisted-deployment-pull-secret
  namespace: open-cluster-management
stringData:
  .dockerconfigjson: "{{ pull_secret.stdout | from_yaml }}"
  type: kubernetes.io/dockerconfigjson