---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pvc-test-rwx
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-rwx
  name: nginx-cephfs-rwx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: nginx-cephfs-rwx
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: nginx-cephfs-rwx
    spec:
      containers:
      - image: nginx
        name: nginx-rwx
        volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www/html
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: cephfs-pvc-test-rwx
          readOnly: false
---
  apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: nginx-rwx
    name: nginx-cephfs-rwx
    namespace: default
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      deployment: nginx-cephfs-rwx
