---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rbd-pvc-test
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-rbd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: nginx-rbd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: nginx-rbd
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          - name: mypvc
            mountPath: /var/lib/www/html
      volumes:
        - name: mypvc
          persistentVolumeClaim:
          claimName: rbd-pvc-test
          readOnly: false
---
  apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: nginx
    name: nginx-rbd
    namespace: default
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      deployment: nginx-rbd
