---
- name: Login to registry and create "{{ registry_auth_file }}"
  containers.podman.podman_login:
    username: '{{ registry_username }}'
    password: '{{ registry_password }}'
    registry: '{{ registry_name }}'
    authfile: '{{ registry_auth_file }}'