# The yaml file is equivalent of the command 
# `oc create secret generic ldap --from-literal=LDAP_BASE_DN=dc=alm,dc=com --from-literal=LDAP_BIND_DN=cn=admin,dc=alm,dc=com --from-literal=LDAP_ADMIN_PASSWORD=adminpassword --from-literal=LDAP_PASSWORD_ATTR=userPassword --from-literal=LDAP_URL=ldap://openldap.default.svc.cluster.local:389 --from-literal=LDAP_USER_SEARCH_BASE=ou=people --from-literal=LDAP_USER_SEARCH_FILTER=uid={0} -n ibmcp4na`
apiVersion: v1
data:
  LDAP_ADMIN_PASSWORD: YWRtaW5wYXNzd29yZA==
  LDAP_BASE_DN: ZGM9YWxtLGRjPWNvbQ==
  LDAP_BIND_DN: Y249YWRtaW4sZGM9YWxtLGRjPWNvbQ==
  LDAP_PASSWORD_ATTR: dXNlclBhc3N3b3Jk
  LDAP_URL: bGRhcDovL29wZW5sZGFwLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6Mzg5Cg==
  LDAP_USER_SEARCH_BASE: b3U9cGVvcGxl
  LDAP_USER_SEARCH_FILTER: dWlkPXswfQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: ldap
  namespace: ibmcp4na
