---
- name: create the {{ dhcp_conf_dir }} directory if it does not exist
  ansible.builtin.file:
    path: "{{ dhcp_conf_dir }}"
    state: directory
    mode: '0755'

- name: set fact for the "include_custom_fqdn variable"
  set_fact:
    include_custom_fqdn: "{{ include_custom_fqdn }}"

- name: create the '{{ dhcp_conf_file }}' for custom fqdn environment
  template:
    src: "dnsmasq.conf.custom_fqdn.j2"
    dest: "{{ dhcp_conf_dir }}/{{ dhcp_conf_file }}"
  when: include_custom_fqdn

- name: create the '{{ dhcp_conf_file }}' for existing fqdn environment
  template:
    src: "dnsmasq.conf.existing_fqdn.j2"
    dest: "{{ dhcp_conf_dir }}/{{ dhcp_conf_file }}"
  when: not include_custom_fqdn