apiVersion: v1
kind: Secret
metadata:
  name: private-repo-ztp
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: {{ ztp_github_repo }}
  password: {{ github_token }}
  username: not-used