# YAML Manifest to create a namespace for the spoke cluster/SNO
---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ sno_node_name }}"
---
#YAML Manifest to create a pull secret object within the spoke cluster/SNO namespace

apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: "{{ sno_node_name }}"
stringData:
  .dockerconfigjson: "{{ pull_secret.stdout | to_yaml }}"  #'$(oc extract -n openshift-config secret/pull-secret  --to=-)'
  type: kubernetes.io/dockerconfigjson
