---
- name: ACM post install/deployment playbook
  hosts: localhost
  roles:
    - role: acm_postdeploy
      vars:
       ansible_work_dir: /tmp/ansible
       # Uncomment the following and include value to overwrite default value of '10Gi'  
       #db_volume_size:       
       file_dest_dir: /tmp/acm_yaml_files
       # Uncomment the following and include value to overwrite default value of '20Gi'
       #fs_volume_size: 
       role_name: acm_postdeploy   