---
- name: Download and apply kubernetes yaml manifests locally
  hosts: localhost

  vars:
    # value of 'stable' can be provided as well
    oc_ver: 4.10.0-rc.8
    argocdcli_ver_tag: v2.5.0
    cp4na_repo_dest: /tmp/siteplanner_yaml_files

  roles:
    - role: helm_install

  tasks:
  - name: Install kubernetes Python module
    ansible.builtin.pip:
      name:
        - kubernetes
        - openshift
        - PyYAML

  - name: unarchive oc
    ansible.builtin.unarchive:
      src: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ oc_ver }}/openshift-client-linux.tar.gz"
      dest: /usr/local/bin/
      remote_src: true

  - name: Download and install ArgoCD CLI from binary file
    ansible.builtin.get_url:
      url: "https://github.com/argoproj/argo-cd/releases/download/{{ argocdcli_ver_tag }}/argocd-linux-amd64"
      dest: /usr/local/bin/argocd
      mode: 0555

  - name: Check if the "{{ cp4na_repo_dest }}" directory exists and create it if it doesn't exist
    ansible.builtin.file:
      path: "{{ file_dest_dir }}"
      state: directory
      mode: '0755'

  - name: Git clone
    ansible.builtin.git:
      accept_hostkey: yes    
      repo: git@github.com:redhat-eets/cp4na_assembly_scripts.git
      dest: "{{ cp4na_repo_dest }}"
      key_file: ~/.ssh/id_rsa
      force: yes