---
- name: Download and apply kubernetes yaml manifests locally
  hosts: localhost

  vars:
    # value of 'stable' can be provided as well
    oc_ver: 4.10.0-rc.8
    argocdcli_ver_tag: v2.5.0
    cp4na_repo_dest: /tmp/siteplanner_yaml_files
    ztp_github_repo: <insert github repo link here>
    github_token: <insert github personal access token here>

  roles:
    - role: helm_install

  tasks:
  - name: Install kubernetes Python module
    ansible.builtin.pip:
      name:
        - kubernetes
        - openshift
        - PyYAML

  - name: unarchive oc
    ansible.builtin.unarchive:
      src: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/{{ oc_ver }}/openshift-client-linux.tar.gz"
      dest: /usr/local/bin/
      remote_src: true

  - name: Download and install ArgoCD CLI from binary file
    ansible.builtin.get_url:
      url: "https://github.com/argoproj/argo-cd/releases/download/{{ argocdcli_ver_tag }}/argocd-linux-amd64"
      dest: /usr/local/bin/argocd
      mode: 0555

  - name: Check if the "{{ cp4na_repo_dest }}" directory exists and create it if it doesn't exist
    ansible.builtin.file:
      path: "{{ cp4na_repo_dest }}"
      state: directory
      mode: '0755'

  - name: Git clone and download CP4NA automation assembly descriptors
    ansible.builtin.git:
      accept_hostkey: yes    
      repo: git@github.com:redhat-eets/cp4na_assembly_scripts.git
      dest: "{{ cp4na_repo_dest }}"
      key_file: ~/.ssh/id_rsa
      force: yes

  - name: Download yaml manifest file template for github account secret from github repo
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/redhat-eets/cp4na/main/ztp_deploy/github-secret.yaml
      dest: "{{ cp4na_repo_dest }}/templates/github-secret.j2"
      mode: '0664'


  - name: Create github account secret yaml manifest file from template
    template:
      src: "{{ cp4na_repo_dest }}/templates/github-secret.j2"
      dest: "{{ cp4na_repo_dest }}/github-secret.yaml"


  - name: Apply creation of github account secret and connect to repo in ArgoCD
    kubernetes.core.k8s:
      state: present
      src: "{{ cp4na_repo_dest }}/github-secret.yaml"
